// config.js
import dotenv from 'dotenv';

dotenv.config();

module.exports = {
  API_TOKEN: process.env.API_TOKEN,
  WHATSAPP_URL: process.env.WHATSAPP_URL,
  WHATSAPP_PHONE_API: process.env.WHATSAPP_PHONE_API,
  WHATSAPP_GROUP_API: process.env.WHATSAPP_GROUP_API,
  WHATSAPP_IMAGE_API: process.env.WHATSAPP_IMAGE_API,
  DB_QUERY_API_ENDPOINT: process.env.DB_QUERY_API_ENDPOINT,
  JOB_IGNORE_FREQUENCY_MINUTES: process.env.JOB_IGNORE_FREQUENCY_MINUTES,
  RUN_JOB_PASSED_MINUTES: process.env.RUN_JOB_PASSED_MINUTES,
  BACWS_API_TIMEOUT: process.env.BACWS_API_TIMEOUT,
  BACWS_RETRY_COUNT: process.env.BACWS_RETRY_COUNT,
  BASIC_AUTH_TOKEN: process.env.BASIC_AUTH_TOKEN,
  COGNITO_TOKEN_URL: process.env.COGNITO_TOKEN_URL,
  BAGCHAT_API_TOKEN: process.env.BAGCHAT_API_TOKEN
};
